networks:
  app_network:
    name: app_network

volumes:
  shared_data:
    driver: local

services:
  psql:
    container_name: psql
    build:
      dockerfile: Docker/Psql/Dockerfile
    restart: always
    networks:
      - app_network
  
  redis:
    container_name: redis
    build:
      context: Docker/Redis/.
      dockerfile: Dockerfile
    restart: always
    expose:
      - 5001
    networks:
      - app_network
  
  nodejs:
    container_name: app
    build:
      context: .
      dockerfile: Docker/Nodejs/Dockerfile
    restart: always
    expose:
      - 3001
      - 4001
    networks:
      - app_network
    depends_on:
      psql:
        condition: service_started
      redis:
        condition: service_started
  
  nginx-certbot:
    container_name: nginx-ssl
    build:
      context: Docker/NginxCertbot/.
      dockerfile: Dockerfile
    restart: always
    ports:
      - 443:443
      - 80:80
    networks:
      - app_network
    depends_on:
      nodejs:
        condition: service_started
    
    
    
  
