networks:
  app_network:
    name: app_network

volumes:
  shared_data:
    driver: local

services:
  psql:
    container_name: psql
    build:
      dockerfile: Docker/Psql/Dockerfile
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "psql -U vieiratechnology -d vieiratechnology -c '\\l' &&>/dev/null" ]
      interval: 5s
      retries: 3
    networks:
      - app_network
  
  redis:
    container_name: redis
    build:
      context: Docker/Redis/.
      dockerfile: Dockerfile
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -u redis://deploy123@127.0.0.1:5001 ping" ]
      interval: 5s
      retries: 3
    expose:
      - 5001
    networks:
      - app_network
  
  nodejs:
    container_name: app
    build:
      context: .
      dockerfile: Docker/Nodejs/Dockerfile
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "/bin/sh /home/deploy/vieiratechnology/tests/healthcheck.sh" ]
      interval: 10s
      retries: 4
    expose:
      - 3001
      - 4001
    networks:
      - app_network
    depends_on:
      psql:
        condition: service_healthy
      redis:
        condition: service_healthy
  
  nginx-certbot:
    container_name: nginx-ssl
    build:
      context: Docker/NginxCertbot/.
      dockerfile: Dockerfile
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "/bin/sh /healthcheck.sh" ]
      interval: 10s
      retries: 3
    ports:
      - 443:443
      - 80:80
    networks:
      - app_network
    depends_on:
      nodejs:
        condition: service_healthy
    
    
    
  