#!/bin/bash
echo "Updating project, please wait."

git pull origin master
npm i --prefix backend
npm i --prefix frontend
npm run build --prefix backend
npm run build --prefix frontend
pm2 restart all

echo "Update finished. Enjoy!"
